- username: admin
  password: adm1n
  type: admin
- username: presAdmin
  password: padm1n
  type: presAdmin
- username: staff
  password: st4ff
  type: staff
- username: balloon
  password: balloonPr1nter
  type: balloon
- username: presentation
  password: presentat1on
  type: public
- username: myicpc
  password: my1cpc
  type: analyst
- username: live
  password: l1ve
  type: analyst
- username: team1
  password: t3am
  type: team
  team_id: '1'
